name: sentry-actions
description: Report workflow failures and job timing.
branding:
  icon: bookmark
  color: gray-dark
inputs:
  GITHUB_TOKEN:
    description: Github token to use to perform operations
    required: true
  SENTRY_DSN:
    description: Sentry configuration
    required: true
  SENTRY_ENVIRONMENT:
    description: Sentry configuration
    required: true
  SENTRY_RELEASE:
    description: Sentry configuration
    required: true
  SENTRY_DEBUG:
    description: Sentry configuration
    required: false
    default: 'false'
outputs:
  html_url:
    description: More info
runs:
  using: docker
  image: 'docker://urcomputeringpal/sentry-actions:main'