name: debug
on:
  workflow_dispatch:
    inputs:
      GITHUB_RUN_ID:
        description: The ID of the GitHub Actions Workflow Run to capture and report to Sentry
        required: true
  workflow_run:
    workflows:
      - docker
      - test
    types: [completed]
jobs:
  trace-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "$GITHUB_CONTEXT"
          false
      - uses: actions/checkout@v2
      - name: test
        id: action
        uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_RUN_ID: ${{ github.event.inputs.GITHUB_RUN_ID }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ENVIRONMENT: debug
          SENTRY_RELEASE: $${{ github.sha }}
          SENTRY_DEBUG: "true"
